Implement slashingRate related APIs
icon-project/goloop pull request #159
Opened 2023-08-03 06:50 UTC by goldworm-icon

* Introduce RevisionPreIISS4(23)
* Implement setSlashingRate() and getSlashingRate()
* Refactor icmodule/penalty.go

2023-08-04 07:02 UTC, eunsoo-icon requested changes

2023-08-04 08:50 UTC, goldworm-icon commented on icon/chainscore_iiss.go
> +	return es.SetSlashingRates(s.newCallContext(s.cc), rates)
Good point!!

2023-08-04 09:28 UTC, goldworm-icon commented on icon/iiss/extension.go
> +		}
I'll fix it

2023-08-07 05:20 UTC, eunsoo-icon approved these changes

2023-08-07 05:35 UTC, merged