Add setNetworkScore has 2 params to `chainMethods`
icon-project/goloop pull request #81
Opened 2022-01-19 09:14 UTC by inwonkim

Add setNetworkScore has 2 params to `chainMethods`(for mainnet compatibility)

* Recognize governance SCORE as network SCORE even not specified with setNetworkScore.
* do not setNetworkScore(governance) on `handleRevisionChange`.

2022-01-19 09:16 UTC, mksong-icon approved these changes

2022-01-19 09:24 UTC, sink772 requested changes

2022-01-19 09:24 UTC, sink772 commented on icon/iiss/icstate/networkvalue.go
> +var AdditionalNetworkScoreKeys = [3]string{CPSKey, RelayKey}
```suggestion
var AdditionalNetworkScoreKeys = []string{CPSKey, RelayKey}
```

2022-01-19 10:19 UTC, goldworm-icon approved these changes

2022-01-20 00:16 UTC, mksong-icon approved these changes

2022-01-20 00:34 UTC, merged